### ISSUE TITLE
[Breakpoint] Local Battery Plugin Does Not Work In Latest Update

### ISSUE THREAD

**Issue by iamcollierlee** [pacjo/SmartspacerPlugins#14]
Hello and good afternoon on my end.

It appears that the local battery plugin is not working for me on the latest update.

Steps to Reproduce:

1. Update or uninstall and reinstall the local battery plugin on the latest update.
2. The charging status will not display anymore.
3. Trying to go to the more settings on any target or complication will crash Smartspacer (immediately) 100% of the time.

My Device:

1. Hardware - Xiaomi Redmi 9, MIUI 13.0.1.0, Android 12 SP1A.210812.016
2. Software Application - Smartspacer 1.7.7
3. Software Plugin - Local Battery Plugin 1.4

Other Notes:

I have tried removing the complications and targets before reinstalling and this did not fix the crashing or get it working.

**Comment by pacjo** [comment]
Hey, thanks for the info.

But it's a bit weird. I just had a pleasure of finally switching from MIUI to Lineage 21 on my tablet. Installed Smartspacer with Local Battery and both work fine. (just checked, more settings open as expected)

Can you get crash logs? [LogFox](https://github.com/F0x1d/LogFox) might help here, since I'm not sure MIUI allows sharing those.

**Comment by iamcollierlee** [comment]
I will grab the logs. For now, here are the screenshots that didn't upload in my last post.
![Screenshot_2024-07-30-16-09-56-538_com teslacoilsw launcher](https://github.com/user-attachments/assets/c1eec7dd-a8d8-482e-a49b-c4df2efd262f)
![Screenshot_2024-07-30-16-09-26-940_com kieronquinn app smartspacer](https://github.com/user-attachments/assets/7da56766-1c96-4c0f-84fc-228464c3b0c7)
![Screenshot_2024-07-30-16-09-36-266_com kieronquinn app smartspacer](https://github.com/user-attachments/assets/15bcf04f-4cf1-4553-99c1-08839e0f728d)
![Screenshot_2024-07-30-16-24-24-191_com teslacoilsw launcher](https://github.com/user-attachments/assets/3480939b-e908-4118-9988-94a46fd44068)

**Comment by pacjo** [comment]
Oh, it does give you an option... you can try sending this.

I'll take a look at it tomorrow.

**Comment by iamcollierlee** [comment]
'''FATAL EXCEPTION: main
Process: nodomain.pacjo.smartspacer.plugin.localbattery, PID: 19631
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
... 1 more
Caused by: org.json.JSONException: End of input at character 0 of
at org.json.JSONTokener.syntaxError(JSONTokener.java:469)
at org.json.JSONTokener.nextValue(JSONTokener.java:101)
at org.json.JSONObject.<init>(JSONObject.java:168)
at org.json.JSONObject.<init>(JSONObject.java:185)
at k2.d.l(Unknown Source:52)
at M.b.l(Unknown Source:51)
at androidx.compose.ui.platform.d0.a(Unknown Source:22)
at D.i.l(Unknown Source:59)
at M.b.l(Unknown Source:51)
at F.r.b(Unknown Source:149)
at androidx.compose.ui.platform.e0.a(Unknown Source:280)
at androidx.compose.ui.platform.N.l(Unknown Source:32)
at M.b.l(Unknown Source:51)
at F.r.b(Unknown Source:149)
at androidx.compose.ui.platform.Q.a(Unknown Source:483)
at androidx.compose.ui.platform.U0.l(Unknown Source:184)
at M.b.l(Unknown Source:51)
at F.r.a(Unknown Source:221)
at androidx.compose.ui.platform.U0.l(Unknown Source:146)
at M.b.l(Unknown Source:51)
at F.r.C(Unknown Source:14)
at F.p.q(Unknown Source:121)
at F.p.k(Unknown Source:10)
at F.v.k(Unknown Source:33)
at F.y0.a(Unknown Source:42)
at F.v.l(Unknown Source:8)
at F.v.d(Unknown Source:2)
at androidx.compose.ui.platform.V0.invoke(Unknown Source:133)
at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:6)
at androidx.compose.ui.platform.WrappedComposition.d(Unknown Source:8)
at androidx.compose.ui.platform.WrappedComposition.c(Unknown Source:18)
at androidx.lifecycle.t.a(Unknown Source:22)
a'''

**Comment by pacjo** [comment]
Alright, I there's a json parsing issue. App probably got killed before it got the chance to finish file operations. 

Can you try to clear app data? It usually helps.

**Comment by iamcollierlee** [comment]
Would you like me to clear all data on the plugin, smart spacer, or both?

**Comment by iamcollierlee** [comment]
I cleared all data on Smart spacer and the issue continued. After adding the plugin complication it did not display. Tapping more settings triggered a crash immediately.

**Comment by pacjo** [comment]
> Would you like me to clear all data on the plugin, smart spacer, or both?

On the plugin, I don't think Smartspacer uses JSON.

and also there's this, so definitely my app is the issue:
```
Process: nodomain.pacjo.smartspacer.plugin.localbattery
```

**Comment by pacjo** [comment]
Did you try clearing the plugin data?

**Comment by pacjo** [comment]
@iamcollierlee ?

**Comment by iamcollierlee** [comment]
Yeah I tried clearing the cache. I will see if there is any other cache that MIUI stores for the app because MIUI is finicky.

**Comment by pacjo** [comment]
I don't remember how MIUI calls it, but at least on AOSP there's storage (user data) *and* cache. Clearing cache won't change anything, clearing storage is what's needed.

![Screenshot_20240805-003221_Settings](https://github.com/user-attachments/assets/06501723-e1ba-4f1c-ab66-f15a9e371bf5)

Though, now that I think about it, uninstalling and reinstalling should have the same effect. (if MIUI is wise enough to purge the leftover data)

**Comment by iamcollierlee** [comment]
I get a notification from their security app that uninstalling apps leaves residue data. I have to open secure to clear it. Sadly. Ima try and see if there is additional data for the app in the settings under storage or ima install and app to get to the normal android storage that the devs kind of tucked away and hid for my firmware.

**Comment by iamcollierlee** [comment]
> I get a notification from their security app that uninstalling apps leaves residue data. I have to open the security app to clear it. Sadly. Ima try and see if there is additional data for the app in the settings under storage or ima install and app to get to the normal android storage that the devs kind of tucked away and hid for my firmware.

The storage had a separate place for data and I cleared it. The battery is showing in smartspacer. Im going to open smartspacer to see that it is resolved.

**Comment by iamcollierlee** [comment]
Yeah it's working now. The more settings open too without crashing.

> [!CAUTION]
> Some MIUI users will need to clear the app data from Settings -> Apps -> Plugin -> Clear All Data.
>
> Long Pressing the Plugin  -> Clear Data -> All Data does not work on some devices.
>
> Clearing data from the MIUI security app does not work on some devices.
